sudo: required
dist: bionic
language: python
python:
- '3.8'
branches:
  only:
  - master
addons:
  apt:
    packages:
    - language-pack-en
    - language-pack-zh-hant
    - language-pack-th
install:
- pip install -r requirements.txt
- make download
script:
- make publish
deploy:
  provider: pages
  repo: siongui/siongui.github.io
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  on:
    branch: master
